name: webflow_api
description: A Webflow CMS Dart package.
  Useful to manage the collections and items of a Webflow project.
  Could be used to create Flutter apps for managing websites' content.
version: 0.1.1

repository: https://github.com/InnoFlutter/webflow_api

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  http: ^1.0.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
