name: webflow_api
description: A Webflow CMS Dart package.
version: 0.1.0

repository: https://github.com/InnoFlutter/webflow_api

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  http: ^0.13.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
